version: "3"
services:
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=dbook
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "pgrep", "mongo"]
      interval: 30s
      timeout: 10s
      retries: 3
  mongo-express:
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    image: mongo-express
    container_name: mongogui
    ports:
      - 8081:8081
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
